/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "storage.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

int
_register_user_rpc_1 (char * *argp, void *result, struct svc_req *rqstp)
{
	return (register_user_rpc_1_svc(*argp, result, rqstp));
}

int
_unregister__user_rpc_1 (char * *argp, void *result, struct svc_req *rqstp)
{
	return (unregister__user_rpc_1_svc(*argp, result, rqstp));
}

int
_connect_user_rpc_1 (connect_arguments  *argp, void *result, struct svc_req *rqstp)
{
	return (connect_user_rpc_1_svc(*argp, result, rqstp));
}

int
_disconnect_user_rpc_1 (char * *argp, void *result, struct svc_req *rqstp)
{
	return (disconnect_user_rpc_1_svc(*argp, result, rqstp));
}

int
_publish_file_rpc_1 (publish_arguments  *argp, void *result, struct svc_req *rqstp)
{
	return (publish_file_rpc_1_svc(*argp, result, rqstp));
}

int
_delete_file_rpc_1 (delete_arguments  *argp, void *result, struct svc_req *rqstp)
{
	return (delete_file_rpc_1_svc(*argp, result, rqstp));
}

int
_list_users_1 (char * *argp, void *result, struct svc_req *rqstp)
{
	return (list_users_1_svc(*argp, result, rqstp));
}

int
_list_content_1 (list_content_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (list_content_1_svc(argp->arg1, argp->arg2, result, rqstp));
}

int
_is_user_registered_1 (char * *argp, void *result, struct svc_req *rqstp)
{
	return (is_user_registered_1_svc(*argp, result, rqstp));
}

int
_is_user_connected_1 (char * *argp, void *result, struct svc_req *rqstp)
{
	return (is_user_connected_1_svc(*argp, result, rqstp));
}

static void
storage_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		char *register_user_rpc_1_arg;
		char *unregister__user_rpc_1_arg;
		connect_arguments connect_user_rpc_1_arg;
		char *disconnect_user_rpc_1_arg;
		publish_arguments publish_file_rpc_1_arg;
		delete_arguments delete_file_rpc_1_arg;
		char *list_users_1_arg;
		list_content_1_argument list_content_1_arg;
		char *is_user_registered_1_arg;
		char *is_user_connected_1_arg;
	} argument;
	union {
		int register_user_rpc_1_res;
		int unregister__user_rpc_1_res;
		int connect_user_rpc_1_res;
		int disconnect_user_rpc_1_res;
		int publish_file_rpc_1_res;
		int delete_file_rpc_1_res;
		UserList list_users_1_res;
		TitleList list_content_1_res;
		int is_user_registered_1_res;
		int is_user_connected_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case REGISTER_USER_RPC:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_register_user_rpc_1;
		break;

	case UNREGISTER__USER_RPC:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_unregister__user_rpc_1;
		break;

	case CONNECT_USER_RPC:
		_xdr_argument = (xdrproc_t) xdr_connect_arguments;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_connect_user_rpc_1;
		break;

	case DISCONNECT_USER_RPC:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_disconnect_user_rpc_1;
		break;

	case PUBLISH_FILE_RPC:
		_xdr_argument = (xdrproc_t) xdr_publish_arguments;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_publish_file_rpc_1;
		break;

	case DELETE_FILE_RPC:
		_xdr_argument = (xdrproc_t) xdr_delete_arguments;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_delete_file_rpc_1;
		break;

	case LIST_USERS:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_UserList;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_list_users_1;
		break;

	case LIST_CONTENT:
		_xdr_argument = (xdrproc_t) xdr_list_content_1_argument;
		_xdr_result = (xdrproc_t) xdr_TitleList;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_list_content_1;
		break;

	case IS_USER_REGISTERED:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_is_user_registered_1;
		break;

	case IS_USER_CONNECTED:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_is_user_connected_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!storage_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (STORAGE, STORAGEVER);

	// transp = svcudp_create(RPC_ANYSOCK);
	// if (transp == NULL) {
	// 	fprintf (stderr, "%s", "cannot create udp service.");
	// 	exit(1);
	// }
	// if (!svc_register(transp, STORAGE, STORAGEVER, storage_1, IPPROTO_UDP)) {
	// 	fprintf (stderr, "%s", "unable to register (STORAGE, STORAGEVER, udp).");
	// 	exit(1);
	// }

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, STORAGE, STORAGEVER, storage_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (STORAGE, STORAGEVER, tcp).");
		exit(1);
	}
	init_server();
	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}