
package src.clientjava.touppercase;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ToUpperCaseServiceService", targetNamespace = "http://webserviceserver.src/", wsdlLocation = "http://localhost:8888/rs?wsdl")
public class ToUpperCaseServiceService
    extends Service
{

    private final static URL TOUPPERCASESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException TOUPPERCASESERVICESERVICE_EXCEPTION;
    private final static QName TOUPPERCASESERVICESERVICE_QNAME = new QName("http://webserviceserver.src/", "ToUpperCaseServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/rs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TOUPPERCASESERVICESERVICE_WSDL_LOCATION = url;
        TOUPPERCASESERVICESERVICE_EXCEPTION = e;
    }

    public ToUpperCaseServiceService() {
        super(__getWsdlLocation(), TOUPPERCASESERVICESERVICE_QNAME);
    }

    public ToUpperCaseServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TOUPPERCASESERVICESERVICE_QNAME, features);
    }

    public ToUpperCaseServiceService(URL wsdlLocation) {
        super(wsdlLocation, TOUPPERCASESERVICESERVICE_QNAME);
    }

    public ToUpperCaseServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TOUPPERCASESERVICESERVICE_QNAME, features);
    }

    public ToUpperCaseServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ToUpperCaseServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ToUpperCaseService
     */
    @WebEndpoint(name = "ToUpperCaseServicePort")
    public ToUpperCaseService getToUpperCaseServicePort() {
        return super.getPort(new QName("http://webserviceserver.src/", "ToUpperCaseServicePort"), ToUpperCaseService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ToUpperCaseService
     */
    @WebEndpoint(name = "ToUpperCaseServicePort")
    public ToUpperCaseService getToUpperCaseServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webserviceserver.src/", "ToUpperCaseServicePort"), ToUpperCaseService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TOUPPERCASESERVICESERVICE_EXCEPTION!= null) {
            throw TOUPPERCASESERVICESERVICE_EXCEPTION;
        }
        return TOUPPERCASESERVICESERVICE_WSDL_LOCATION;
    }

}
