/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "storage.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
register_user_rpc_1(char *arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, REGISTER_USER_RPC,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
unregister__user_rpc_1(char *arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, UNREGISTER__USER_RPC,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
connect_user_rpc_1(connect_arguments arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, CONNECT_USER_RPC,
		(xdrproc_t) xdr_connect_arguments, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
disconnect_user_rpc_1(char *arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, DISCONNECT_USER_RPC,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
publish_file_rpc_1(publish_arguments arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, PUBLISH_FILE_RPC,
		(xdrproc_t) xdr_publish_arguments, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
delete_file_rpc_1(delete_arguments arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, DELETE_FILE_RPC,
		(xdrproc_t) xdr_delete_arguments, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
list_users_1(char *arg1, UserList *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, LIST_USERS,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &arg1,
		(xdrproc_t) xdr_UserList, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
list_content_1(char *arg1, char *arg2, TitleList *clnt_res,  CLIENT *clnt)
{
	list_content_1_argument arg;
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	return (clnt_call (clnt, LIST_CONTENT, (xdrproc_t) xdr_list_content_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_TitleList, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
is_user_registered_1(char *arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, IS_USER_REGISTERED,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
is_user_connected_1(char *arg1, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, IS_USER_CONNECTED,
		(xdrproc_t) xdr_wrapstring, (caddr_t) &arg1,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
