/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "storage.h"

bool_t
xdr_connect_arguments (XDR *xdrs, connect_arguments *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->name, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->port, 7))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->ip, 16))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_publish_arguments (XDR *xdrs, publish_arguments *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->name, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->file_name, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->file_description, 256))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_delete_arguments (XDR *xdrs, delete_arguments *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->name, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->file_name, 256))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_UserServer (XDR *xdrs, UserServer *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->name, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->port, 7))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->ip, 16))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_UserList (XDR *xdrs, UserList *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->UserList_val, (u_int *) &objp->UserList_len, ~0,
		sizeof (UserServer), (xdrproc_t) xdr_UserServer))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Title (XDR *xdrs, Title *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->file_name, 256))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_TitleList (XDR *xdrs, TitleList *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->TitleList_val, (u_int *) &objp->TitleList_len, ~0,
		sizeof (Title), (xdrproc_t) xdr_Title))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_list_content_1_argument (XDR *xdrs, list_content_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->arg1, 256))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->arg2, 256))
		 return FALSE;
	return TRUE;
}
